name: smplc CI

on: [push]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    container:
      image: luishsu/smplc
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        cc: clang
        cxx: clang++
        build-type: Debug
        configure-options: -G Ninja
        run-test: true
        install-build: false
